model:
  hparams:
    learning_rate: 0.001
    num_epochs: 150
    d_h: 32
    output_dim: 1
    batch_size: 8
  
input_path: "data/processed/iuphar_labeled2.pt"
output_path: "output"

training:
  checkpoint_path:
  save_path: "output/checkpoints"